# Importing requests libraries

In [ ]:
import pandas as pd
import numpy as np

# 1. Basic Data Inspection

In [ ]:
df_raw = pd.read_csv('../../data/raw/anime_catalog.csv')
df = df_raw.copy()
df.sample(5)

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,...,shikimori_url,worldart_rating,worldart_url,kinopoisk_rating,kinopoisk_url,mal_rating,mal_url,comments_count,reviews_count,url
3207,Воин четырёх стихий,Burning Wind Ocean Earth Samurai Lord | Bushil...,8975,вышел,Спешл,Осень 2013,R-17+,Меха | Фантастика | Фэнтези | Экшен,Оригинальная идея,Kinema Citrus | Orange,...,NaN,NaN,NaN,6.4,//kinopoisk.ru/film/818784,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/voin-chet...
8046,Сильваниан Фэмилиз: Чудесные дни Фрейи,Sylvanian Families: Freya no Wonder Days | シルバ...,23496,вышел,Сериал,Осень 2025,G,Повседневность,Линейка игрушек,LandQ studios,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/sylvanian...
2947,Голубой гигант,Blue Giant | Блакитний гігант,11335,вышел,Полнометражный фильм,Зима 2023,PG-13,Сэйнэн | Музыка,Манга,NUT,...,NaN,NaN,NaN,7.8,//kinopoisk.ru/film/5018659,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/goluboy-g...
3717,Дикая семёрка,Wild 7 | Wild 7: Biker Knights | Дика сімка | ...,20810,вышел,OVA,Зима 1994,R-17+,Сёнэн | Драма | Преступный мир | Экшен | Полиц...,Манга,animate Film | Studio Kikan,...,NaN,NaN,NaN,NaN,//kinopoisk.ru/film/842231,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/dikaya-se...
5720,Дорохедоро 2,Dorohedoro (Zoku-hen) | Dorohedoro 2nd Season ...,11704,онгоинг,Сериал,Весна 2026,R-17+,Сэйнэн | Комедия | Ужасы | Фэнтези | Экшен,Манга,MAPPA,...,NaN,NaN,NaN,8.0,//kinopoisk.ru/film/1311143,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/dorohedoro-2

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10142 entries, 0 to 10141
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_ru          10142 non-null  str
 1   alt_names         10140 non-null  str
 2   anime_id          10142 non-null  int64
 3   status            10142 non-null  str
 4   type              10142 non-null  str
 5   year              9897 non-null   str
 6   age_rating        10142 non-null  str
 7   genres            10109 non-null  str
 8   source            10142 non-null  str
 9   studio            9698 non-null   str
 10  director          8502 non-null   str
 11  dubbing           8360 non-null   str
 12  site_rating       10142 non-null  float64
 13  site_votes        10142 non-null  int64
 14  site_views        10142 non-null  str
 15  shikimori_rating  0 non-null      float64
 16  shikimori_url     0 non-null      float64
 17  worldart_rating   0 non-null      float64
 18  worldart_url      0 non-null      float64
 19  kinopoisk_rating  4209 non-null   float64
 20  kinopoisk_url     6959 non-null   str
 21  mal_rating        0 non-null      float64
 22  mal_url           0 non-null      float64
 23  comments_count    0 non-null      float64
 24  reviews_count     0 non-null      float64
 25  url               10142 non-null  str
dtypes: float64(10), int64(2), str(14)
memory usage: 2.0 MB

In [ ]:
df.describe()

,anime_id,site_rating,site_votes,shikimori_rating,shikimori_url,worldart_rating,worldart_url,kinopoisk_rating,mal_rating,mal_url,comments_count,reviews_count
count,10142.000000,10142.000000,10142.000000,0.0,0.0,0.0,0.0,4209.000000,0.0,0.0,0.0,0.0
mean,9006.145139,6.414001,261.780319,NaN,NaN,NaN,NaN,6.982965,NaN,NaN,NaN,NaN
std,5790.678239,1.830632,686.914423,NaN,NaN,NaN,NaN,0.798113,NaN,NaN,NaN,NaN
min,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,3.400000,NaN,NaN,NaN,NaN
25%,5749.250000,5.840000,14.000000,NaN,NaN,NaN,NaN,6.400000,NaN,NaN,NaN,NaN
50%,8362.500000,6.760000,37.000000,NaN,NaN,NaN,NaN,6.900000,NaN,NaN,NaN,NaN
75%,11157.750000,7.520000,165.000000,NaN,NaN,NaN,NaN,7.600000,NaN,NaN,NaN,NaN
max,28053.000000,9.540000,9435.000000,NaN,NaN,NaN,NaN,9.100000,NaN,NaN,NaN,NaN

In [ ]:
print('data types: ')
df.dtypes

data types:

title_ru                str
alt_names               str
anime_id              int64
status                  str
type                    str
year                    str
age_rating              str
genres                  str
source                  str
studio                  str
director                str
dubbing                 str
site_rating         float64
site_votes            int64
site_views              str
shikimori_rating    float64
shikimori_url       float64
worldart_rating     float64
worldart_url        float64
kinopoisk_rating    float64
kinopoisk_url           str
mal_rating          float64
mal_url             float64
comments_count      float64
reviews_count       float64
url                     str
dtype: object

In [ ]:
print('num of rows and columns: ')
df.shape

num of rows and columns:

(10142, 26)

In [ ]:
print('columns names: ')
df.columns

columns names:

Index(['title_ru', 'alt_names', 'anime_id', 'status', 'type', 'year',
       'age_rating', 'genres', 'source', 'studio', 'director', 'dubbing',
       'site_rating', 'site_votes', 'site_views', 'shikimori_rating',
       'shikimori_url', 'worldart_rating', 'worldart_url', 'kinopoisk_rating',
       'kinopoisk_url', 'mal_rating', 'mal_url', 'comments_count',
       'reviews_count', 'url'],
      dtype='str')

# 2. Missing Values

In [ ]:
df.isnull().sum()

title_ru                0
alt_names               2
anime_id                0
status                  0
type                    0
year                  245
age_rating              0
genres                 33
source                  0
studio                444
director             1640
dubbing              1782
site_rating             0
site_votes              0
site_views              0
shikimori_rating    10142
shikimori_url       10142
worldart_rating     10142
worldart_url        10142
kinopoisk_rating     5933
kinopoisk_url        3183
mal_rating          10142
mal_url             10142
comments_count      10142
reviews_count       10142
url                     0
dtype: int64

In [ ]:
#detecting missing values
missing = df.isnull().sum()
missing_pct = missing / df.shape[0] * 100
missing_above_20 = missing_pct[missing_pct > 20]

print('Columns with missing values > 20%:')
print('------------------------------------------------------------------------------------')
for col, pct in missing_above_20.items():
    print(f'{col}: {missing[col]} missing ({pct:.2f}%)')
print('------------------------------------------------------------------------------------')
print(f'Total columns affected: {len(missing_above_20)}')

Columns with missing values > 20%:
------------------------------------------------------------------------------------
shikimori_rating: 10142 missing (100.00%)
shikimori_url: 10142 missing (100.00%)
worldart_rating: 10142 missing (100.00%)
worldart_url: 10142 missing (100.00%)
kinopoisk_rating: 5933 missing (58.50%)
kinopoisk_url: 3183 missing (31.38%)
mal_rating: 10142 missing (100.00%)
mal_url: 10142 missing (100.00%)
comments_count: 10142 missing (100.00%)
reviews_count: 10142 missing (100.00%)
------------------------------------------------------------------------------------
Total columns affected: 10

In [ ]:
#dropping empty columns
missing_100 = missing_pct[missing_pct == 100]

for col, pct in missing_100.items():
    df = df.drop(columns=col)
    print(f'{col} has been dropped because it has 100% missing values')

df.shape

shikimori_rating has been dropped because it has 100% missing values
shikimori_url has been dropped because it has 100% missing values
worldart_rating has been dropped because it has 100% missing values
worldart_url has been dropped because it has 100% missing values
mal_rating has been dropped because it has 100% missing values
mal_url has been dropped because it has 100% missing values
comments_count has been dropped because it has 100% missing values
reviews_count has been dropped because it has 100% missing values

(10142, 18)

In [ ]:
#column has only 2 miss, so filling it with empty string
df['alt_names'] = df['alt_names'].fillna('')

#filling missing values in 'year' column with median value
df['year'] = df['year'].str.extract('(\d{4})').astype(float)  # Extracting year as a 4-digit number and converting to float
df['year'] = df['year'].fillna(df['year'].median())
df['year'] = df['year'].astype(int)

#important column for our analysis, so filling missing values with 'Unknown'
df['genres'] = df['genres'].fillna('Unknown')



#filling missing values with median value
df['director'] = df['director'].fillna('Unknown')
df['dubbing'] = df['dubbing'].fillna('Unknown')
df['studio'] = df['studio'].fillna('Unknown')

#dropping columns that are not useful for our analysis and have many missing values
df = df.drop(columns=['kinopoisk_rating', 'kinopoisk_url'])

<>:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
/tmp/ipykernel_67499/2556997499.py:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['year'] = df['year'].str.extract('(\d{4})').astype(float)  # Extracting year as a 4-digit number and converting to float

In [ ]:
df.sample(25)

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,director,dubbing,site_rating,site_votes,site_views,url
9453,Вольтрон: Легендарный защитник 5,Voltron: Legendary Defender 5 | Вольтрон: Леге...,10953,вышел,Сериал,2018,PG-13,Сёнэн | Меха | Приключения | Фантастика,Оригинальная идея,DreamWorks Animation SKG | Studio Mir,Стив Ан | Юджин Ли,Unknown,6.89,9,8 415 просмотров,https://old.yummyani.me/catalog/item/voltron-l...
198,Проект Кей: Семь историй. Потерянный маленький...,K Seven Stories Lost Small World ~檻の向こうに~ | K:...,9278,вышел,Полнометражный фильм,2018,PG-13,Экшен | Суперспособности | Сверхъестественное,Оригинальная идея,GoHands,Судзуки Синго,Unknown,7.31,90,16 894 просмотра,https://old.yummyani.me/catalog/item/proekt-ke...
9877,Лисы Тиронуп,Chironup no Kitsune | Chironuppu no Kitsune | ...,8732,вышел,Полнометражный фильм,1987,G,Драма,книга,Group TAC,Имадзава Тэцуо,Anything Group,6.00,12,4 423 просмотра,https://old.yummyani.me/catalog/item/lisy-tironup
3148,Девушка из оперы!!,Kageki Shojo!! | Kageki Shoujo!! | Opera Girl!...,6327,вышел,Сериал,2021,PG-13,Сёдзё | Драма | Музыка | Школьная жизнь,Манга,Pine Jam,Ёнэда Кадзухиро,StudioBand | AniDUB | AniStar | Studio Band | ...,7.78,94,27 367 просмотров,https://old.yummyani.me/catalog/item/devushka-...
2476,Штурмовые ведьмы: 501-й отряд поднимается в небо!,Strike Witches: 501 Butai Hasshin Shimasu!! | ...,1343,вышел,Сериал,2019,PG-13,Сёнэн | Комедия | Фантастика | Военная тематика,Манга,Acca effe | Giga Production,Ито Фумио,AniDUB,6.27,48,35 987 просмотров,https://old.yummyani.me/catalog/item/shturmovy...
1641,Один из отвергнутых: Изгой — Рекап,Yi Ren Zhi Xia Recap | Відкинутий: Вигнанець —...,11844,вышел,Спешл,2018,R-17+,Мистика | Экшен | Суперспособности | Не японск...,Маньхуа,Haoliners Animation League,Ван Синь | Ли Хаолин,SHIZA Project | SovetRomantica,6.31,36,14 013 просмотров,https://old.yummyani.me/catalog/item/odin-iz-o...
8085,"Небесный стрелок: Возвращение/Туда, куда дует ...",Gunslinger Stratos The Animation: Kikan/Kaze n...,11899,вышел,ONA,2015,PG-13,Фантастика | Экшен,Видеоигра,A-1 Pictures,Unknown,SHIZA Project,5.21,14,4 360 просмотров,https://old.yummyani.me/catalog/item/nebesniy-...
8731,Сверхновая звезда,Chaoxinxing | Nova Hero | Supernova | Наднова ...,25798,анонс,ONA,2015,PG-13,Приключения | Фэнтези | Экшен | Не японское,Оригинальная идея,Qingxiang Culture,Unknown,Unknown,0.00,0,7 569 просмотров,https://old.yummyani.me/catalog/item/chaoxinxing
2169,Ради своей дочери я смогу победить даже короля...,"If It's for My Daughter, I'd Even Defeat a Dem...",1217,вышел,Сериал,2019,PG-13,Фэнтези | Повседневность,Ранобэ,Maho Film,Янасэ Хироюки,AniDUB | AniLibria | Onibaku | SHIZA Project,7.64,688,82 095 просмотров,https://old.yummyani.me/catalog/item/radi-svoe...
8880,Поцелуй в глазик,Kiss me on the Apple of my Eye | Kiss wa Hitom...,8927,вышел,OVA,1993,PG-13,Сёдзё | Драма | Романтика,Манга,Madhouse,Окубо Томихико,Onibaku,5.33,12,4 074 просмотра,https://old.yummyani.me/catalog/item/poceluy-v...
4257,Туалетный мальчик Ханако,Jibaku Shounen Hanako-kun | Toilet-Bound Hanak...,4846,вышел,Сериал,2020,PG-13,Сёнэн | Комедия | Фэнтези | Школьная жизнь | С...,Манга,Lerche,Андо Масаоми,SHIZA Project | Mamoru | Abe | Wozwald | Kitsu...,7.99,1054,178 706 просмотров,https://old.yummyani.me/catalog/item/tualetnyy...
5785,Госслужащие за работой,Servant x Service | Держслужбовці за роботою |...,435,вышел,Сериал,2013,PG-13,Сэйнэн | Комедия | Романтика | Повседневность,Манга,A-1 Pictures,Ямамото Ясутака,AniDUB | AniLibria | SHIZA Project,7.68,142,51 843 просмотра,https://old.yummyani.me/catalog/item/gossluzha...
970,Воровка-камикадзе Жанна,Divine Wind Thief Jeanne | Kamikaze Kaitou Jea...,8518,вышел,Сериал,1999,PG-13,Махо-сёдзё | Сёдзё | Детектив | Драма | Комеди...,Манга,Toei Animation,Умэдзава Ацутоси,metalrus | TFanigroup,6.84,19,10 676 просмотров,https://old.yummyani.me/catalog/item/vorovka-k...
3790,Провожающая в последний путь Фрирен 2,Frieren at the Funeral Season 2 | Frieren: Bey...,15084,вышел,Сериал,2026,PG-13,Сёнэн | Драма | Приключения | Фэнтези | Магия ...,Манга,Madhouse,Китагава Томоя,Dream Cast | Ket | Indominus Rex | SteycheR | ...,9.07,3575,3 439 949 просмотров,https://old.yummyani.me/catalog/item/provozhay...
211,Мазафакер,M★F★K★Z | MFKZ | Mutafukaz | Ублюдыши | ムタフカズ ...,6817,вышел,Полнометражный фильм,2017,R-17+,Фантастика | Экшен | Суперспособности | Психол...,Оригинальная идея,Studio 4°C | Ankama Animations,Танака Эйко | Фредерик Пюэк | Энтони Ру,Грубо Говоря канал | Галина Карабчук | Света М...,7.33,69,20 522 просмотра,https://old.yummyani.me/catalog/item/mazafaker
9892,Невезучая ведьма Дореми: Диез. Фильм,Bothersome Witch Doremi Sharp | Ojamajo Doremi...,10190,вышел,Короткометражный фильм,2000,G,Сёдзё | Комедия | Фэнтези,Оригинальная идея,Toei Animation,Игараси Такуя,Unknown,5.36,11,4 018 просмотров,https://old.yummyani.me/catalog/item/nevezucha...
9885,Дорохедоро: Дьявольский бонус,Dorohedoro OVA | Dorohedoro: Bonus Curse or Ex...,11366,вышел,Спешл,2020,R-17+,Сэйнэн | Комедия | Ужасы | Фэнтези | Экшен,Манга,MAPPA,Хаяси Юитиро,Amazing Dubbing | Zozya | Yu_ki | Sharakam | I...,7.63,238,70 402 просмотра,https://old.yummyani.me/catalog/item/dorohedor...
5068,Один: Блистательный сезон,ONE ～輝く季節へ～ | One: Kagayaku Kisetsu e | One: T...,7706,вышел,Неизвестно,2001,PG-13,Драма | Сверхъестественное,видеоигра,Triple X,Кагэяма Сигэнори,Люб. Одноголосый,5.40,15,4 867 просмотров,https://old.yummyani.me/catalog/item/odin-blis...
3797,"Вперёд, Анпанман! (фильм #15)","Sore Ike! Anpanman: Ruby no Negai | Вперед, Ан...",6594,вышел,Короткометражный фильм,2003,PG,Комедия | Приключения,книга,Tokyo Movie,Яно Хироюки,Unknown,5.40,15,4 738 просмотров,https://old.yummyani.me/catalog/item/vpered-an...
9263,Внук Нурарихёна — Рекап,Nurarihyon no Mago Episode 12.5 and Episode 24...,12732,вышел,Спешл,2010,PG-13,Сёнэн | Демоны | Экшен | Сверхъестественное,Манга,Studio Deen,Нисимура Дзюндзи,Unknown,6.88,41,11 922 просмотра,https://old.yummyani.me/catalog/item/vnuk-nura...
8407,Клуб стрельбы из лука — Фильм,Tsurune Movie: Hajimari no Issha | Tsurune the...,10215,вышел,Полнометражный фильм,2022,PG-13,Бисёнэн | Драма | Спорт | Школьная жизнь,Ранобэ,Kyoto Animation,Ямамура Такуя,AniMaunt | Leoneo | MissClick | Bvia | J.Dark ...,7.25,56,18 203 просмотра,https://old.yummyani.me/catalog/item/klub-stre...
4330,Бегущий по лезвию: Чёрный лотос,BLADE RUNNER – BLACK LOTUS | Blade Runner: Bla...,6233,вышел,Сериал,2021,R-17+,Детектив | Триллер | Фантастика | Перестрелки ...,фильм,Sola Digital Arts,Арамаки Синдзи,Crunchyroll | AniLibria | HDrezka Studio | SHI...,6.03,58,25 353 просмотра,https://old.yummyani.me/catalog/item/beguschiy...
4693,Фигура 17: Цубаса и Хикару,Figure 17 - Tsubasa and Hikaru | Figure 17: Ts...,6126,вышел,Сериал,2001,PG-13,Драма | Фантастика | Повседневность,оригинальная идея,OLM,Такахаси Наохито,Persona99,5.38,13,4 279 просмотров,https://old.yummyani.me/catalog/item/figura-17...
2666,Невероятные приключения ДжоДжо: Каменный океан,JoJo no Kimyou na Bouken Part 6: Stone Ocean |...,986,вышел,ONA,2021,R-17+,Сёнэн | Детектив | Драма | Комедия | Приключен...,Манга,David Production,Судзуки Кэнъити | Като Тосиюки,AniLibria | Dejz | Nuts | Zozya | Cleo-chan | ...,7.73,1570,157 995 просмотров,https://old.yummyani.me/catalog/item/neveroyat...
8984,Страна чудес,Shen Lan Qi Yu Wushuang Zhu | The Land of Mira...,4820,вышел,ONA,2022,PG-13,Фэнтези | Экшен | Не японское | Китайское 3D,Новелла,High Energy Studio,Unknown,AniStar | Любительский двухголосый | ПВА ШОУ,6.64,33,22 992 просмотра,https://old.yummyani.me/catalog/item/strana-ch...

# 3. Data Types & Format Issues

In [ ]:
print(df.dtypes)

title_ru           str
alt_names          str
anime_id         int64
status             str
type               str
year             int64
age_rating         str
genres             str
source             str
studio             str
director           str
dubbing            str
site_rating    float64
site_votes       int64
site_views         str
url                str
dtype: object

In [ ]:
#converting columns to numeric
df['site_views'] = df['site_views'].str.extract('(\d+)').astype(int)
df['site_views']

<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
/tmp/ipykernel_67499/2985304771.py:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['site_views'] = df['site_views'].str.extract('(\d+)').astype(int)

0         6
1         6
2         6
3         4
4        10
         ..
10137    36
10138    28
10139     7
10140    10
10141     9
Name: site_views, Length: 10142, dtype: int64

In [ ]:
#splitting columns with multiple values into lists
df['genres'] = df['genres'].str.split('|')
df['alt_names'] = df['alt_names'].str.split('|')
df['studio'] = df['studio'].str.split('|')
df['director'] = df['director'].str.split('|')
df['dubbing'] = df['dubbing'].str.split('|')

In [ ]:
df

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,director,dubbing,site_rating,site_votes,site_views,url
0,Моя история продолжается сегодня,"[Kyou, Watashi no Monogatari ga Hashirimasu. ,...",10800,вышел,ONA,2023,G,"[Повседневность , Спорт]",Оригинальная идея,[Studio Colorido],[Синго Ямасита],[AniLane],6.74,19,6,https://old.yummyani.me/catalog/item/moya-isto...
1,Детектив Конан: Цель — Когоро! Секретное рассл...,[Detective Conan OVA 05: The Target is Kogoro!...,8258,вышел,OVA,2005,PG-13,"[Сёнэн , Детектив , Комедия , Приключения ,...",Манга,[TMS Entertainment],[Сато Масато],[Persona99],6.65,23,6,https://old.yummyani.me/catalog/item/detektiv-...
2,Сердце дракона: Хроника исследования мира духов,"[Dragon Heart: Adventures Beyond This World , ...",18742,вышел,Полнометражный фильм,2025,G,"[Фэнтези , Драконы , Сверхъестественное]",Оригинальная идея,[HS Pictures Studio],[Имакакэ Исаму],[Unknown],5.60,5,6,https://old.yummyani.me/catalog/item/dragon-he...
3,Госпожа Кэйфуку,"[Keifuku-san , Keifukusan , Пані Кейфуку , ...",6905,вышел,ONA,2017,G,[Фэнтези],Оригинальная идея,[Yaoyorozu],[Тацуки],"[Panzu.info , ХЗ Лол]",5.28,18,4,https://old.yummyani.me/catalog/item/gospozha-...
4,Ветер из Лояна: Таинственный мальчик,"[Feng qi luo yang zhi shen ji shao nian , Fen...",6198,вышел,ONA,2021,PG-13,"[Детектив , Приключения , Фэнтези , Экшен ,...",Оригинальная идея,[Chosen],[Unknown],"[AniStar , Автоперевод , ПВА ШОУ]",6.42,19,10,https://old.yummyani.me/catalog/item/veter-iz-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10137,Проект Кей: Возвращение королей,"[K , K 2nd Season , K RETURN OF KINGS , K-P...",7262,вышел,Сериал,2015,PG-13,"[Фэнтези , Экшен , Суперспособности]",Оригинальная идея,[GoHands],"[Судзуки Синго , Канадзава Хиромити]","[AniDUB , AniLibria , Onibaku , SHIZA Project]",7.79,323,36,https://old.yummyani.me/catalog/item/proekt-ke...
10138,Великий блюз!,"[Grablu! , Grand Blues! , Guraburu! , Грабл...",1561,вышел,Малометражный сериал,2020,PG-13,"[Приключения , Фэнтези]",Манга,"[W-Toon Studio , DMM.futureworks]",[Мории Кэнсиро],"[AniLibria , Hoopoe , Renie , Frederica Izz...",5.23,30,28,https://old.yummyani.me/catalog/item/velikij-b...
10139,Мэйз: Пространство мегавзрыва,"[Maze bakunetsu jikû , Maze: The Mega-Burst S...",6910,вышел,Сериал,1997,PG-13,"[Сёнэн , Комедия , Меха , Пилотируемые робо...",Ранобэ,[J.C.Staff],[Судзуки Ику],"[Animegroup , Get Smart Group , Persona99]",5.73,15,7,https://old.yummyani.me/catalog/item/meyz-pros...
10140,Нарутару,"[Narutaru: Mukuro naru hoshi tama taru ko , S...",9458,вышел,Сериал,2003,R-17+,"[Сэйнэн , Драма , Триллер , Фэнтези]",Манга,[Planet],[Иино Тосиаки],[AniDUB],6.13,23,10,https://old.yummyani.me/catalog/item/narutaru
10141,Человеческие отношения,"[Homeroom Affairs , Human Relations , Tanin ...",7178,вышел,OVA,1994,R+,"[Этти , Комедия , Романтика , Школьная жизнь]",Манга,[J.C.Staff],[Сэкита Осаму],[Unknown],5.95,22,9,https://old.yummyani.me/catalog/item/chelovech...

# 4. Duplicate Data

In [ ]:
#checking and resolving duplicate anime_id
dup_ids = df[df['anime_id'].duplicated(keep=False)]
print(f"Rows with duplicate anime_id: {len(dup_ids)}")

#keeping only the first occurrence
df = df.drop_duplicates(subset='anime_id', keep='first')
print(f"Shape after deduplication: {df.shape}")

Rows with duplicate anime_id: 0
Shape after deduplication: (10142, 16)

# 5. Invalid or Suspicious Values

In [ ]:
#manually checking for issues in the data
issues = {}

issues['year_out_of_range'] = df[(df['year'] < 1900) | (df['year'] > 2030)]
issues['rating_out_of_range'] = df[(df['site_rating'] < 0) | (df['site_rating'] > 10)]
issues['votes_negative'] = df[df['site_votes'] < 0]
issues['views_negative'] = df[df['site_views'] < 0]
issues['duplicate_anime_id'] = df[df['anime_id'].duplicated(keep=False)]
issues['empty_title'] = df[df['title_ru'].isna()]
issues['empty_type'] = df[df['type'].isna()]
issues['empty_status'] = df[df['status'].isna()]
issues['empty_genres'] = df[df['genres'].isna()]

In [ ]:
issues

{'year_out_of_range': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'rating_out_of_range': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'votes_negative': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'views_negative': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'duplicate_anime_id': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_title': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_type': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_status': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_genres': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: []}

In [ ]:
num_cols = ['year', 'site_rating', 'site_votes', 'site_views']


#z-score method
z_scores = (df[num_cols] - df[num_cols].mean()) / df[num_cols].std()
z_outliers = np.abs(z_scores) > 3

#iqr method
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

iqr_outliers = (df[num_cols] < (Q1 - 1.5 * IQR)) | (df[num_cols] > (Q3 + 1.5 * IQR))

#merging outliers from both methods
outliers = z_outliers | iqr_outliers

#rows with issues
df_outliers = df[outliers.any(axis=1)]

#marking
df['suspicious'] = outliers.any(axis=1)

#checking
df_outliers[num_cols].sample(50)


df = df.drop(columns='suspicious')

We examined the outliers and suspicious values, but concluded that in this case they cannot be analyzed reliably due to the very high variance. We also believe these values are valid, as such data can realistically occur. Therefore, we decided not to remove these outliers

In [ ]:
# final validation
print("Final shape")
print(df.shape)

print("Remaining missing values")
print(df.isnull().sum())

print("Data types")
print(df.dtypes)

Final shape
(10142, 16)
Remaining missing values
title_ru       0
alt_names      0
anime_id       0
status         0
type           0
year           0
age_rating     0
genres         0
source         0
studio         0
director       0
dubbing        0
site_rating    0
site_votes     0
site_views     0
url            0
dtype: int64
Data types
title_ru           str
alt_names       object
anime_id         int64
status             str
type               str
year             int64
age_rating         str
genres          object
source             str
studio          object
director        object
dubbing         object
site_rating    float64
site_votes       int64
site_views       int64
url                str
dtype: object

In [ ]:
df

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,director,dubbing,site_rating,site_votes,site_views,url
0,Моя история продолжается сегодня,"[Kyou, Watashi no Monogatari ga Hashirimasu. ,...",10800,вышел,ONA,2023,G,"[Повседневность , Спорт]",Оригинальная идея,[Studio Colorido],[Синго Ямасита],[AniLane],6.74,19,6,https://old.yummyani.me/catalog/item/moya-isto...
1,Детектив Конан: Цель — Когоро! Секретное рассл...,[Detective Conan OVA 05: The Target is Kogoro!...,8258,вышел,OVA,2005,PG-13,"[Сёнэн , Детектив , Комедия , Приключения ,...",Манга,[TMS Entertainment],[Сато Масато],[Persona99],6.65,23,6,https://old.yummyani.me/catalog/item/detektiv-...
2,Сердце дракона: Хроника исследования мира духов,"[Dragon Heart: Adventures Beyond This World , ...",18742,вышел,Полнометражный фильм,2025,G,"[Фэнтези , Драконы , Сверхъестественное]",Оригинальная идея,[HS Pictures Studio],[Имакакэ Исаму],[Unknown],5.60,5,6,https://old.yummyani.me/catalog/item/dragon-he...
3,Госпожа Кэйфуку,"[Keifuku-san , Keifukusan , Пані Кейфуку , ...",6905,вышел,ONA,2017,G,[Фэнтези],Оригинальная идея,[Yaoyorozu],[Тацуки],"[Panzu.info , ХЗ Лол]",5.28,18,4,https://old.yummyani.me/catalog/item/gospozha-...
4,Ветер из Лояна: Таинственный мальчик,"[Feng qi luo yang zhi shen ji shao nian , Fen...",6198,вышел,ONA,2021,PG-13,"[Детектив , Приключения , Фэнтези , Экшен ,...",Оригинальная идея,[Chosen],[Unknown],"[AniStar , Автоперевод , ПВА ШОУ]",6.42,19,10,https://old.yummyani.me/catalog/item/veter-iz-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10137,Проект Кей: Возвращение королей,"[K , K 2nd Season , K RETURN OF KINGS , K-P...",7262,вышел,Сериал,2015,PG-13,"[Фэнтези , Экшен , Суперспособности]",Оригинальная идея,[GoHands],"[Судзуки Синго , Канадзава Хиромити]","[AniDUB , AniLibria , Onibaku , SHIZA Project]",7.79,323,36,https://old.yummyani.me/catalog/item/proekt-ke...
10138,Великий блюз!,"[Grablu! , Grand Blues! , Guraburu! , Грабл...",1561,вышел,Малометражный сериал,2020,PG-13,"[Приключения , Фэнтези]",Манга,"[W-Toon Studio , DMM.futureworks]",[Мории Кэнсиро],"[AniLibria , Hoopoe , Renie , Frederica Izz...",5.23,30,28,https://old.yummyani.me/catalog/item/velikij-b...
10139,Мэйз: Пространство мегавзрыва,"[Maze bakunetsu jikû , Maze: The Mega-Burst S...",6910,вышел,Сериал,1997,PG-13,"[Сёнэн , Комедия , Меха , Пилотируемые робо...",Ранобэ,[J.C.Staff],[Судзуки Ику],"[Animegroup , Get Smart Group , Persona99]",5.73,15,7,https://old.yummyani.me/catalog/item/meyz-pros...
10140,Нарутару,"[Narutaru: Mukuro naru hoshi tama taru ko , S...",9458,вышел,Сериал,2003,R-17+,"[Сэйнэн , Драма , Триллер , Фэнтези]",Манга,[Planet],[Иино Тосиаки],[AniDUB],6.13,23,10,https://old.yummyani.me/catalog/item/narutaru
10141,Человеческие отношения,"[Homeroom Affairs , Human Relations , Tanin ...",7178,вышел,OVA,1994,R+,"[Этти , Комедия , Романтика , Школьная жизнь]",Манга,[J.C.Staff],[Сэкита Осаму],[Unknown],5.95,22,9,https://old.yummyani.me/catalog/item/chelovech...

In [ ]:
#saving cleaned dataframe
df.to_csv('../../data/processed/anime_catalog_clean.csv', index=False)
print("Saved successfully!")

Saved successfully!