# Importing requests libraries

In [44]:
import pandas as pd
import numpy as np

# 1. Basic Data Inspection

In [45]:
df_raw = pd.read_csv('../data/raw/anime_catalog.csv')
df = df_raw.copy()
df.sample(5)

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,...,shikimori_url,worldart_rating,worldart_url,kinopoisk_rating,kinopoisk_url,mal_rating,mal_url,comments_count,reviews_count,url
4172,Неприятности одной девушки-зомби,Aru Zombie Shoujo no Sainan PV | Aru Zonbi Sho...,9116,вышел,ONA,Лето 2018,PG-13,Ужасы | Фэнтези | Зомби | Экшен,Ранобэ,Gonzo,...,NaN,NaN,NaN,NaN,//kinopoisk.ru/film/1121075,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/nepriyatn...
5079,Войны супер-роботов (2005),SRWOG | Super Robot Taisen OG The Animation | ...,9357,вышел,Неизвестно,2005,PG-13,Сёнэн | Меха | Фантастика | Космос | Экшен,видеоигра,Brain's Base,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/voyny-sup...
7113,Вампир Холмс,VAMPIRE HOLMES | Вампір Холмс,9958,вышел,Сериал,Весна 2015,PG-13,Детектив | Комедия | Сверхъестественное,Мобильная игра,Studio! Cucuri,...,NaN,NaN,NaN,NaN,//kinopoisk.ru/film/1380516,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/vampir-holms
7504,Отражение,The Reflection | Віддзеркалення | Отражение: П...,9781,вышел,Сериал,Лето 2017,PG-13,Экшен | Суперспособности,Оригинальная идея,Studio Deen,...,NaN,NaN,NaN,NaN,//kinopoisk.ru/film/1043653,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/otrazhenie
1659,The Ribbon Hero,THE RIBBON HERO リボンヒーロー,27995,анонс,ONA,Лето 2026,Неизвестно,Сёдзё | Драма | Приключения | Романтика | Фэнт...,Оригинальная идея,Outline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/the-ribbo...

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10142 entries, 0 to 10141
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_ru          10142 non-null  str
 1   alt_names         10140 non-null  str
 2   anime_id          10142 non-null  int64
 3   status            10142 non-null  str
 4   type              10142 non-null  str
 5   year              9897 non-null   str
 6   age_rating        10142 non-null  str
 7   genres            10109 non-null  str
 8   source            10142 non-null  str
 9   studio            9698 non-null   str
 10  director          8502 non-null   str
 11  dubbing           8360 non-null   str
 12  site_rating       10142 non-null  float64
 13  site_votes        10142 non-null  int64
 14  site_views        10142 non-null  str
 15  shikimori_rating  0 non-null      float64
 16  shikimori_url     0 non-null      float64
 17  worldart_rating   0 non-null      float64
 18  worldart_url      0 non-null      float64
 19  kinopoisk_rating  4209 non-null   float64
 20  kinopoisk_url     6959 non-null   str
 21  mal_rating        0 non-null      float64
 22  mal_url           0 non-null      float64
 23  comments_count    0 non-null      float64
 24  reviews_count     0 non-null      float64
 25  url               10142 non-null  str
dtypes: float64(10), int64(2), str(14)
memory usage: 2.0 MB

In [47]:
df.describe()

,anime_id,site_rating,site_votes,shikimori_rating,shikimori_url,worldart_rating,worldart_url,kinopoisk_rating,mal_rating,mal_url,comments_count,reviews_count
count,10142.000000,10142.000000,10142.000000,0.0,0.0,0.0,0.0,4209.000000,0.0,0.0,0.0,0.0
mean,9006.145139,6.414001,261.780319,NaN,NaN,NaN,NaN,6.982965,NaN,NaN,NaN,NaN
std,5790.678239,1.830632,686.914423,NaN,NaN,NaN,NaN,0.798113,NaN,NaN,NaN,NaN
min,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,3.400000,NaN,NaN,NaN,NaN
25%,5749.250000,5.840000,14.000000,NaN,NaN,NaN,NaN,6.400000,NaN,NaN,NaN,NaN
50%,8362.500000,6.760000,37.000000,NaN,NaN,NaN,NaN,6.900000,NaN,NaN,NaN,NaN
75%,11157.750000,7.520000,165.000000,NaN,NaN,NaN,NaN,7.600000,NaN,NaN,NaN,NaN
max,28053.000000,9.540000,9435.000000,NaN,NaN,NaN,NaN,9.100000,NaN,NaN,NaN,NaN

In [48]:
print('data types: ')
df.dtypes

data types:

title_ru                str
alt_names               str
anime_id              int64
status                  str
type                    str
year                    str
age_rating              str
genres                  str
source                  str
studio                  str
director                str
dubbing                 str
site_rating         float64
site_votes            int64
site_views              str
shikimori_rating    float64
shikimori_url       float64
worldart_rating     float64
worldart_url        float64
kinopoisk_rating    float64
kinopoisk_url           str
mal_rating          float64
mal_url             float64
comments_count      float64
reviews_count       float64
url                     str
dtype: object

In [49]:
print('num of rows and columns: ')
df.shape

num of rows and columns:

(10142, 26)

In [50]:
print('columns names: ')
df.columns

columns names:

Index(['title_ru', 'alt_names', 'anime_id', 'status', 'type', 'year',
       'age_rating', 'genres', 'source', 'studio', 'director', 'dubbing',
       'site_rating', 'site_votes', 'site_views', 'shikimori_rating',
       'shikimori_url', 'worldart_rating', 'worldart_url', 'kinopoisk_rating',
       'kinopoisk_url', 'mal_rating', 'mal_url', 'comments_count',
       'reviews_count', 'url'],
      dtype='str')

# 2. Missing Values

In [51]:
df.isnull().sum()

title_ru                0
alt_names               2
anime_id                0
status                  0
type                    0
year                  245
age_rating              0
genres                 33
source                  0
studio                444
director             1640
dubbing              1782
site_rating             0
site_votes              0
site_views              0
shikimori_rating    10142
shikimori_url       10142
worldart_rating     10142
worldart_url        10142
kinopoisk_rating     5933
kinopoisk_url        3183
mal_rating          10142
mal_url             10142
comments_count      10142
reviews_count       10142
url                     0
dtype: int64

In [52]:
#detecting missing values
missing = df.isnull().sum()
missing_pct = missing / df.shape[0] * 100
missing_above_20 = missing_pct[missing_pct > 20]

print('Columns with missing values > 20%:')
print('------------------------------------------------------------------------------------')
for col, pct in missing_above_20.items():
    print(f'{col}: {missing[col]} missing ({pct:.2f}%)')
print('------------------------------------------------------------------------------------')
print(f'Total columns affected: {len(missing_above_20)}')

Columns with missing values > 20%:
------------------------------------------------------------------------------------
shikimori_rating: 10142 missing (100.00%)
shikimori_url: 10142 missing (100.00%)
worldart_rating: 10142 missing (100.00%)
worldart_url: 10142 missing (100.00%)
kinopoisk_rating: 5933 missing (58.50%)
kinopoisk_url: 3183 missing (31.38%)
mal_rating: 10142 missing (100.00%)
mal_url: 10142 missing (100.00%)
comments_count: 10142 missing (100.00%)
reviews_count: 10142 missing (100.00%)
------------------------------------------------------------------------------------
Total columns affected: 10

In [53]:
#dropping empty columns
missing_100 = missing_pct[missing_pct == 100]

for col, pct in missing_100.items():
    df = df.drop(columns=col)
    print(f'{col} has been dropped because it has 100% missing values')

df.shape

shikimori_rating has been dropped because it has 100% missing values
shikimori_url has been dropped because it has 100% missing values
worldart_rating has been dropped because it has 100% missing values
worldart_url has been dropped because it has 100% missing values
mal_rating has been dropped because it has 100% missing values
mal_url has been dropped because it has 100% missing values
comments_count has been dropped because it has 100% missing values
reviews_count has been dropped because it has 100% missing values

(10142, 18)

In [54]:
#column has only 2 miss, so filling it with empty string
df['alt_names'] = df['alt_names'].fillna('')

#filling missing values in 'year' column with median value
df['year'] = df['year'].str.extract('(\d{4})').astype(float)  # Extracting year as a 4-digit number and converting to float
df['year'] = df['year'].fillna(df['year'].median())
df['year'] = df['year'].astype(int)

#important column for our analysis, so filling missing values with 'Unknown'
df['genres'] = df['genres'].fillna('Unknown')



#filling missing values with median value
df['director'] = df['director'].fillna('Unknown')
df['dubbing'] = df['dubbing'].fillna('Unknown')
df['studio'] = df['studio'].fillna('Unknown')

#dropping columns that are not useful for our analysis and have many missing values
df = df.drop(columns=['kinopoisk_rating', 'kinopoisk_url'])

<>:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\nuras\AppData\Local\Temp\ipykernel_14560\2556997499.py:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['year'] = df['year'].str.extract('(\d{4})').astype(float)  # Extracting year as a 4-digit number and converting to float

In [55]:
df.sample(25)

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,director,dubbing,site_rating,site_votes,site_views,url
494,Прекрасная Хина,Hina | Hina is Beautiful | Прекрасна Хіна | ひな,12147,анонс,Полнометражный фильм,2015,Неизвестно,Сёнэн | Драма | Романтика | Повседневность,Манга,Unknown,Иваидзава Кэндзи,Unknown,0.00,0,3 560 просмотров,https://old.yummyani.me/catalog/item/prekrasna...
3203,Призрачный Наньтин,Ghosts in Nanting | Gu Wei Nan Ting | Guwei Na...,11805,вышел,ONA,2025,PG-13,Комедия | Мистика | Приключения | Ужасы | Экше...,Маньхуа,2:10 AM Animation,Unknown,AniMaunt | Творческая студия МИР | MDA,7.55,40,71 115 просмотров,https://old.yummyani.me/catalog/item/prizrachn...
3178,Семья защитников Земли,Chikyû bôei kazoku | Chikyuu Bouei Kazoku | Th...,5893,вышел,Сериал,2001,PG-13,Драма | Комедия | Фантастика | Экшен,Оригинальная идея,Group TAC,Кимура Тэцу,Эхо в коробкЕ,5.55,11,5 952 просмотра,https://old.yummyani.me/catalog/item/semya-zas...
7948,Банановая рыба,Banana Fish | Бананова риба | Рыбка-бананка,7866,вышел,Сериал,2018,R-17+,Сёдзё | Драма | Преступный мир | Приключения |...,Манга,MAPPA,Уцуми Хироко,SHIZA Project | DroED | Лизавета | Daelit | Ni...,8.28,947,189 894 просмотра,https://old.yummyani.me/catalog/item/rybka-ban...
2482,Век дракона,Dragon Century | Ryuu Seiki | Вік дракона | 竜世紀,7651,вышел,OVA,1988,R-17+,Фантастика | Фэнтези | Демоны | Экшен,Манга,AIC,Фукумото Киёси,Люб. Двухголосый | Любительский двухголосый,4.90,10,3 972 просмотра,https://old.yummyani.me/catalog/item/vek-drakona
9950,Волшебный учитель Нэгима! Финал,Gekijouban Negima | Mahou Sensei Negima! Movie...,5608,вышел,Полнометражный фильм,2011,PG-13,Комедия | Приключения | Фэнтези | Сверхъестест...,Манга,Shaft,Симбо Акиюки,AniDUB,6.05,40,14 746 просмотров,https://old.yummyani.me/catalog/item/volshebny...
264,Люпен III: Принцесса морского бриза,Lupin III: Princess of the Breeze - Kakusareta...,751,вышел,Спешл,2013,PG-13,Сэйнэн | Комедия | Приключения | Экшен,Манга,TMS Entertainment,Канасаки Такаоми,AniDUB | LE-Production | Persona99,6.85,27,7 943 просмотра,https://old.yummyani.me/catalog/item/lyupen-ii...
406,Моя геройская академия,Boku no Hero Academia TV-1 | My Hero Academia ...,866,вышел,Сериал,2016,PG-13,Сёнэн | Комедия | Приключения | Экшен | Суперс...,Манга,Bones,Нагасаки Кэндзи,AniLibria | Aemi | Reni | AniDUB | Jam | AniDu...,7.99,3517,1 350 579 просмотров,https://old.yummyani.me/catalog/item/moya-gero...
2200,Роллинг Рёта,Korogashi Ryouta | Вырубальщик Рёта | Лихач Рё...,5176,вышел,OVA,1990,R+,Сэйнэн | Комедия | Экшен | Эротика,Неизвестно,Knack Productions,Unknown,Amazing Dubbing,5.14,7,5 294 просмотра,https://old.yummyani.me/catalog/item/rolling-reta
6783,Юмэрия,Yumeria | Юмерія | ゆめりあ,9594,вышел,Сериал,2004,PG-13,Этти | Комедия | Экшен | Суперспособности | Гарем,видеоигра,Studio Deen,Мотонага Кэйтаро,AniDUB | OSLIKt | Persona99,6.62,24,10 240 просмотров,https://old.yummyani.me/catalog/item/yumeriya
4180,Любовь с незапамятных времен 2,Ai Zai Xiyuan Qian 2nd Season | Immemorial Lov...,5920,вышел,ONA,2021,PG-13,Романтика | Фантастика | Фэнтези | Экшен | Не ...,Маньхуа,Taikong Works,Unknown,AniStar | AniStar Многоголосый,6.86,28,13 167 просмотров,https://old.yummyani.me/catalog/item/lyubov-s-...
5864,Мобильный воин Гандам: Грозовой сектор — Фильм...,Kidou Senshi Gundam Thunderbolt: Bandit Flower...,9315,вышел,Полнометражный фильм,2017,R+,Сёнэн | Драма | Меха | Фантастика | Космос | Э...,Манга,Sunrise,Unknown,AniDUB,7.00,24,10 475 просмотров,https://old.yummyani.me/catalog/item/mobilnyy-...
1167,Тэнти — лишний! Галактическая полиция,Tenchi Muyo! GXP | Tenchi Muyou | Tenchi Muyou...,9502,вышел,Сериал,2002,PG-13,Сёнэн | Комедия | Меха | Фантастика | Космос |...,Оригинальная идея,AIC,Ватанабэ Синъити,AniDUB | Haruka,6.84,38,19 693 просмотра,https://old.yummyani.me/catalog/item/tenti-lis...
732,Механические руки,Mecha-Ude | Mechanical Arms | Механические рук...,8639,вышел,ONA,2018,PG-13,Меха | Фантастика | Экшен,Оригинальная идея,TriF Studio,Окамото Саэ,AniDUB | AniMaunt | AnimeVost,6.74,98,30 258 просмотров,https://old.yummyani.me/catalog/item/mehaniche...
7609,Верный Гиндзиро,Koha Ginjiro | Kouha Ginjirou | Trusty Ginjiro...,6462,вышел,OVA,1991,PG-13,Сёнэн | Драма | Экшен | Школьная жизнь,Манга,Bandai Visual | animate Film | Visual 80,Исигуро Койти,Amazing Dubbing,5.71,14,4 849 просмотров,https://old.yummyani.me/catalog/item/vernyy-gi...
5499,Продавец фантазий,Guai Xiang Shou | Whimsical Wish | Продавець ф...,13276,вышел,ONA,2024,PG-13,Комедия | Фэнтези | Не японское,Оригинальная идея,HuaMei Animation,Unknown,StudioBand | AniMaunt,6.86,28,13 716 просмотров,https://old.yummyani.me/catalog/item/guai-xian...
5991,Бандиты,Gangsta. | GANGSTA. ギャングスタ | Gyangusuta | Банд...,7274,вышел,Сериал,2015,R-17+,Сэйнэн | Драма | Приключения | Экшен,Манга,Manglobe,Мурасэ Сюко,AniDUB | AniLibria | AniMedia | LE-Production ...,8.17,947,128 258 просмотров,https://old.yummyani.me/catalog/item/bandity
6086,Чудачество любви не помеха Lite,Chu-2 Byo demo Koi ga Shitai! Lite | Chunibyo ...,8251,вышел,ONA,2012,PG-13,Сэйнэн | Комедия | Школьная жизнь,Ранобэ,Kyoto Animation,Исихара Тацуя,AniFilm | Оканэ,7.25,334,29 808 просмотров,https://old.yummyani.me/catalog/item/chudaches...
2067,Истинные чудотворные рыцари,Yoroi Shin Den Samurai Troopers | Справжні див...,21263,вышел,Сериал,2026,PG-13,Приключения | Фантастика | Самураи,Оригинальная идея,Sunrise,Фудзита Ёити,AniStar & DEEP | Михаил Глушенков | Евгений Цы...,4.72,29,41 391 просмотр,https://old.yummyani.me/catalog/item/istinnye-...
8539,Детское подразделение 2,Kiddy Girl-AND | Kiddy Grade 2 | Дитячий підро...,8511,вышел,Сериал,2009,PG-13,Комедия | Фантастика | Экшен | Суперспособности,оригинальная идея,Satelight,Гото Кэйдзи,AniDUB | Persona99 | Persona99 & MaxDamage,6.09,11,5 286 просмотров,https://old.yummyani.me/catalog/item/detskoe-p...
5058,Инициал D: Боевая стадия 3,Initial D Battle Stage 3 | Ініціал D: Бойова с...,6712,вышел,OVA,2021,PG-13,Драма | Экшен | Спорт | Машины,Манга,SynergySP,Мицуо Хасимото,Unknown,8.16,138,34 434 просмотра,https://old.yummyani.me/catalog/item/inicial-d...
5775,"Скромные герои: Краб, яйцо и человек-невидимка",Chiisana Eiyuu: Kani to Tamago to Toumei Ninge...,5222,вышел,Короткометражный фильм,2018,G,Драма | Приключения | Фэнтези | Экшен,Оригинальная идея,Studio Ponoc,Ёнэбаяси Хиромаса | Момосэ Ёсиюки | Ямасита Ак...,Anything Group | Milirina | Sad_Kit | AniDUB,6.85,66,19 764 просмотра,https://old.yummyani.me/catalog/item/3-istorii...
2600,Евангелион 1.11: Ты (не) один,Evangelion 1.0: You Are (Not) Alone | Evangeli...,367,вышел,Полнометражный фильм,2007,R-17+,Сёнэн | Драма | Меха | Пилотируемые роботы | Т...,Оригинальная идея,Khara,Масаюки Ямагути,ReAnimedia | Борис Алексеев | Елена Симанович ...,7.84,1132,90 846 просмотров,https://old.yummyani.me/catalog/item/evangelio...
7039,Мисс Монохром 3,Miss Monochrome The Animation 3 | Міс Монохром...,9011,вышел,Малометражный сериал,2015,G,Комедия | Музыка | Повседневность,Оригинал,Lidenfilms | SANZIGEN,Ивасаки Ёсиаки,AniDUB | Persona99 | SHIZA Project,6.73,26,6 788 просмотров,https://old.yummyani.me/catalog/item/miss-mono...
9255,Нинку: Спецвыпуск,Ninku: Knife no Bohyou | Ninkuu: Knife no Bohy...,11451,вышел,Спешл,1994,PG-13,Сёнэн | Комедия | Приключения | Экшен | Боевые...,Манга,Pierrot,Абэ Нориюки,Unknown,7.00,6,3 043 просмотра,https://old.yummyani.me/catalog/item/ninku-spe...

# 3. Data Types & Format Issues

In [56]:
print(df.dtypes)

title_ru           str
alt_names          str
anime_id         int64
status             str
type               str
year             int64
age_rating         str
genres             str
source             str
studio             str
director           str
dubbing            str
site_rating    float64
site_votes       int64
site_views         str
url                str
dtype: object

In [57]:
#converting columns to numeric
df['site_views'] = df['site_views'].str.replace(' ', '', regex=False).str.extract(r'(\d+)').astype(int)
df['site_views']

0         6634
1         6389
2         6705
3         4853
4        10515
         ...
10137    36912
10138    28634
10139     7420
10140    10428
10141     9578
Name: site_views, Length: 10142, dtype: int64

In [58]:
#splitting columns with multiple values into lists
df['genres'] = df['genres'].str.split('|')
df['alt_names'] = df['alt_names'].str.split('|')
df['studio'] = df['studio'].str.split('|')
df['director'] = df['director'].str.split('|')
df['dubbing'] = df['dubbing'].str.split('|')

In [59]:
df

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,director,dubbing,site_rating,site_votes,site_views,url
0,Моя история продолжается сегодня,"[Kyou, Watashi no Monogatari ga Hashirimasu. ,...",10800,вышел,ONA,2023,G,"[Повседневность , Спорт]",Оригинальная идея,[Studio Colorido],[Синго Ямасита],[AniLane],6.74,19,6634,https://old.yummyani.me/catalog/item/moya-isto...
1,Детектив Конан: Цель — Когоро! Секретное рассл...,[Detective Conan OVA 05: The Target is Kogoro!...,8258,вышел,OVA,2005,PG-13,"[Сёнэн , Детектив , Комедия , Приключения ,...",Манга,[TMS Entertainment],[Сато Масато],[Persona99],6.65,23,6389,https://old.yummyani.me/catalog/item/detektiv-...
2,Сердце дракона: Хроника исследования мира духов,"[Dragon Heart: Adventures Beyond This World , ...",18742,вышел,Полнометражный фильм,2025,G,"[Фэнтези , Драконы , Сверхъестественное]",Оригинальная идея,[HS Pictures Studio],[Имакакэ Исаму],[Unknown],5.60,5,6705,https://old.yummyani.me/catalog/item/dragon-he...
3,Госпожа Кэйфуку,"[Keifuku-san , Keifukusan , Пані Кейфуку , ...",6905,вышел,ONA,2017,G,[Фэнтези],Оригинальная идея,[Yaoyorozu],[Тацуки],"[Panzu.info , ХЗ Лол]",5.28,18,4853,https://old.yummyani.me/catalog/item/gospozha-...
4,Ветер из Лояна: Таинственный мальчик,"[Feng qi luo yang zhi shen ji shao nian , Fen...",6198,вышел,ONA,2021,PG-13,"[Детектив , Приключения , Фэнтези , Экшен ,...",Оригинальная идея,[Chosen],[Unknown],"[AniStar , Автоперевод , ПВА ШОУ]",6.42,19,10515,https://old.yummyani.me/catalog/item/veter-iz-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10137,Проект Кей: Возвращение королей,"[K , K 2nd Season , K RETURN OF KINGS , K-P...",7262,вышел,Сериал,2015,PG-13,"[Фэнтези , Экшен , Суперспособности]",Оригинальная идея,[GoHands],"[Судзуки Синго , Канадзава Хиромити]","[AniDUB , AniLibria , Onibaku , SHIZA Project]",7.79,323,36912,https://old.yummyani.me/catalog/item/proekt-ke...
10138,Великий блюз!,"[Grablu! , Grand Blues! , Guraburu! , Грабл...",1561,вышел,Малометражный сериал,2020,PG-13,"[Приключения , Фэнтези]",Манга,"[W-Toon Studio , DMM.futureworks]",[Мории Кэнсиро],"[AniLibria , Hoopoe , Renie , Frederica Izz...",5.23,30,28634,https://old.yummyani.me/catalog/item/velikij-b...
10139,Мэйз: Пространство мегавзрыва,"[Maze bakunetsu jikû , Maze: The Mega-Burst S...",6910,вышел,Сериал,1997,PG-13,"[Сёнэн , Комедия , Меха , Пилотируемые робо...",Ранобэ,[J.C.Staff],[Судзуки Ику],"[Animegroup , Get Smart Group , Persona99]",5.73,15,7420,https://old.yummyani.me/catalog/item/meyz-pros...
10140,Нарутару,"[Narutaru: Mukuro naru hoshi tama taru ko , S...",9458,вышел,Сериал,2003,R-17+,"[Сэйнэн , Драма , Триллер , Фэнтези]",Манга,[Planet],[Иино Тосиаки],[AniDUB],6.13,23,10428,https://old.yummyani.me/catalog/item/narutaru
10141,Человеческие отношения,"[Homeroom Affairs , Human Relations , Tanin ...",7178,вышел,OVA,1994,R+,"[Этти , Комедия , Романтика , Школьная жизнь]",Манга,[J.C.Staff],[Сэкита Осаму],[Unknown],5.95,22,9578,https://old.yummyani.me/catalog/item/chelovech...

# 4. Duplicate Data

In [60]:
#checking and resolving duplicate anime_id
dup_ids = df[df['anime_id'].duplicated(keep=False)]
print(f"Rows with duplicate anime_id: {len(dup_ids)}")

#keeping only the first occurrence
df = df.drop_duplicates(subset='anime_id', keep='first')
print(f"Shape after deduplication: {df.shape}")

Rows with duplicate anime_id: 0
Shape after deduplication: (10142, 16)

# 5. Invalid or Suspicious Values

In [61]:
#manually checking for issues in the data
issues = {}

issues['year_out_of_range'] = df[(df['year'] < 1900) | (df['year'] > 2030)]
issues['rating_out_of_range'] = df[(df['site_rating'] < 0) | (df['site_rating'] > 10)]
issues['votes_negative'] = df[df['site_votes'] < 0]
issues['views_negative'] = df[df['site_views'] < 0]
issues['duplicate_anime_id'] = df[df['anime_id'].duplicated(keep=False)]
issues['empty_title'] = df[df['title_ru'].isna()]
issues['empty_type'] = df[df['type'].isna()]
issues['empty_status'] = df[df['status'].isna()]
issues['empty_genres'] = df[df['genres'].isna()]

In [62]:
issues

{'year_out_of_range': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'rating_out_of_range': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'votes_negative': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'views_negative': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'duplicate_anime_id': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_title': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_type': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_status': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_genres': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: []}

In [63]:
num_cols = ['year', 'site_rating', 'site_votes', 'site_views']


#z-score method
z_scores = (df[num_cols] - df[num_cols].mean()) / df[num_cols].std()
z_outliers = np.abs(z_scores) > 3

#iqr method
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

iqr_outliers = (df[num_cols] < (Q1 - 1.5 * IQR)) | (df[num_cols] > (Q3 + 1.5 * IQR))

#merging outliers from both methods
outliers = z_outliers | iqr_outliers

#rows with issues
df_outliers = df[outliers.any(axis=1)]

#marking
df['suspicious'] = outliers.any(axis=1)

#checking
df_outliers[num_cols].sample(50)


df = df.drop(columns='suspicious')

We examined the outliers and suspicious values, but concluded that in this case they cannot be analyzed reliably due to the very high variance. We also believe these values are valid, as such data can realistically occur. Therefore, we decided not to remove these outliers

In [64]:
# final validation
print("Final shape")
print(df.shape)

print("Remaining missing values")
print(df.isnull().sum())

print("Data types")
print(df.dtypes)

Final shape
(10142, 16)
Remaining missing values
title_ru       0
alt_names      0
anime_id       0
status         0
type           0
year           0
age_rating     0
genres         0
source         0
studio         0
director       0
dubbing        0
site_rating    0
site_votes     0
site_views     0
url            0
dtype: int64
Data types
title_ru           str
alt_names       object
anime_id         int64
status             str
type               str
year             int64
age_rating         str
genres          object
source             str
studio          object
director        object
dubbing         object
site_rating    float64
site_votes       int64
site_views       int64
url                str
dtype: object

In [65]:
df

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,director,dubbing,site_rating,site_votes,site_views,url
0,Моя история продолжается сегодня,"[Kyou, Watashi no Monogatari ga Hashirimasu. ,...",10800,вышел,ONA,2023,G,"[Повседневность , Спорт]",Оригинальная идея,[Studio Colorido],[Синго Ямасита],[AniLane],6.74,19,6634,https://old.yummyani.me/catalog/item/moya-isto...
1,Детектив Конан: Цель — Когоро! Секретное рассл...,[Detective Conan OVA 05: The Target is Kogoro!...,8258,вышел,OVA,2005,PG-13,"[Сёнэн , Детектив , Комедия , Приключения ,...",Манга,[TMS Entertainment],[Сато Масато],[Persona99],6.65,23,6389,https://old.yummyani.me/catalog/item/detektiv-...
2,Сердце дракона: Хроника исследования мира духов,"[Dragon Heart: Adventures Beyond This World , ...",18742,вышел,Полнометражный фильм,2025,G,"[Фэнтези , Драконы , Сверхъестественное]",Оригинальная идея,[HS Pictures Studio],[Имакакэ Исаму],[Unknown],5.60,5,6705,https://old.yummyani.me/catalog/item/dragon-he...
3,Госпожа Кэйфуку,"[Keifuku-san , Keifukusan , Пані Кейфуку , ...",6905,вышел,ONA,2017,G,[Фэнтези],Оригинальная идея,[Yaoyorozu],[Тацуки],"[Panzu.info , ХЗ Лол]",5.28,18,4853,https://old.yummyani.me/catalog/item/gospozha-...
4,Ветер из Лояна: Таинственный мальчик,"[Feng qi luo yang zhi shen ji shao nian , Fen...",6198,вышел,ONA,2021,PG-13,"[Детектив , Приключения , Фэнтези , Экшен ,...",Оригинальная идея,[Chosen],[Unknown],"[AniStar , Автоперевод , ПВА ШОУ]",6.42,19,10515,https://old.yummyani.me/catalog/item/veter-iz-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10137,Проект Кей: Возвращение королей,"[K , K 2nd Season , K RETURN OF KINGS , K-P...",7262,вышел,Сериал,2015,PG-13,"[Фэнтези , Экшен , Суперспособности]",Оригинальная идея,[GoHands],"[Судзуки Синго , Канадзава Хиромити]","[AniDUB , AniLibria , Onibaku , SHIZA Project]",7.79,323,36912,https://old.yummyani.me/catalog/item/proekt-ke...
10138,Великий блюз!,"[Grablu! , Grand Blues! , Guraburu! , Грабл...",1561,вышел,Малометражный сериал,2020,PG-13,"[Приключения , Фэнтези]",Манга,"[W-Toon Studio , DMM.futureworks]",[Мории Кэнсиро],"[AniLibria , Hoopoe , Renie , Frederica Izz...",5.23,30,28634,https://old.yummyani.me/catalog/item/velikij-b...
10139,Мэйз: Пространство мегавзрыва,"[Maze bakunetsu jikû , Maze: The Mega-Burst S...",6910,вышел,Сериал,1997,PG-13,"[Сёнэн , Комедия , Меха , Пилотируемые робо...",Ранобэ,[J.C.Staff],[Судзуки Ику],"[Animegroup , Get Smart Group , Persona99]",5.73,15,7420,https://old.yummyani.me/catalog/item/meyz-pros...
10140,Нарутару,"[Narutaru: Mukuro naru hoshi tama taru ko , S...",9458,вышел,Сериал,2003,R-17+,"[Сэйнэн , Драма , Триллер , Фэнтези]",Манга,[Planet],[Иино Тосиаки],[AniDUB],6.13,23,10428,https://old.yummyani.me/catalog/item/narutaru
10141,Человеческие отношения,"[Homeroom Affairs , Human Relations , Tanin ...",7178,вышел,OVA,1994,R+,"[Этти , Комедия , Романтика , Школьная жизнь]",Манга,[J.C.Staff],[Сэкита Осаму],[Unknown],5.95,22,9578,https://old.yummyani.me/catalog/item/chelovech...

In [67]:
#saving cleaned dataframe
df.to_csv('../data/processed/anime_catalog_clean.csv', index=False)
print("Saved successfully!")

Saved successfully!